### ISSUE TITLE
Discussion: Any thoughts on Differentiable for ROS?

### ISSUE THREAD

**Issue by nidegen** [tgu/RosSwift#1]
Swift for Tensorflow introduced the concept of differentiablity for [swift functions](https://github.com/apple/swift/blob/master/docs/DifferentiableProgramming.md#robotics).

Any thoughts on that?

I was thinking of experimenting with some sort of state estimator built with it. Would it make sense to build a RosSwift node?

**Comment by tgu** [comment]
Yes! I have been thinking about that. A generic extended Kalman filter would be interesting to implement

**Comment by nidegen** [comment]
Cool. I will let you know if I start something with like that. Maybe not before it is merged into swift though. Hope to see it make into Swift 6.

**Comment by nidegen** [comment]
I found that Dallaert is starting up a [Sensor Fusion lib](https://github.com/borglab/SwiftFusion). Swift for Robotics will get exciting:)
