### ISSUE TITLE
Installation resources

### ISSUE THREAD

**Issue by MarcoDotIO** [tgu/RosSwift#3]
Hello,

I am an iOS programmer who is wanting to expand out to using other packages. Would you be able to provide resources on installing this package for Xcode 11. I really do thank you for still maintaining this package too!

**Comment by tgu** [comment]
Hello, 

It should be straightforward, see guide [here](https://medium.com/@bartekzabicki/how-to-add-dependency-spm-into-project-using-xcode11-84a2914f8f1). Even better to use Xcode 12
