### ISSUE TITLE
Installing via Package Manager causes compile error from several targets in the library.

### ISSUE THREAD

**Issue by agcoesbenr** [tgu/RosSwift#5]
### Expected behavior
Library is correctly imported into iOS project

### Actual behavior
Packet manager prompts what targets to include. Instructions / readme doesen't say which to include. Selecting all wil cause several targets in the Library to fail.

### Steps to reproduce

1. Install via Packet Manager in Xcode 13
2. Select all targets  to include when prompted
3. Try to compile your iOS app

### If possible, minimal yet complete reproducer code (or URL to code)

![image](https://user-images.githubusercontent.com/93992823/141443296-d8e3b1b5-7abd-4f35-a790-8a7c685b28ff.png)

### RosSwift version/commit hash

Nevest release

### Swift & OS version (output of `swift --version && uname -a`)

Swift 5 + Xcode 13

### Notes
I also don't understand why listener, publisher, msgbuilder and msgs is puclic target to include.
Is something wrong in the library configuration?

**Comment by tgu** [comment]
It should be sufficient to only include the RosSwift library from the Package

**Comment by agcoesbenr** [comment]
Removing the targets in question made it work allthough it's not nescessary to include other than RosSwift as stated above.
