### ISSUE TITLE
Stuck Creating iOS App

### ISSUE THREAD

**Issue by SachinSAgrawal** [tgu/RosSwift#8]
This is an odd question, but I was wondering if there was (or you could provide) a working iOS app that can be a publisher or subscriber. I created a new project in Xcode and added RosSwift as a package dependency, but now didn't know where to go from there to create an app that can publish data. I only need to publish 7 values that the user can select on a screen. Any help would be greatly appreciated! My Macbook is running macOS Ventura (13.4.1) and I'm running Xcode version 15 beta 3 (15A5195k).

**Comment by tgu** [comment]
See the example app
